exec XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_SUPPLIER_ADDRESS;
exec XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_SUPPLIER;
exec XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_SUPPLIER_CONTACT;
exec XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_ORDER_HEADERS;
exec XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_ORDER_LINES;
exec XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_INVOICE_HOLDS;
exec XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_INVOICE_HEADERS;
exec XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_INVOICE_LINES;

select * from XXBCM_SUPPLIER_ADDRESS_TBL;
select * from XXBCM_SUPPLIERS_TBL;
select * from XXBCM_SUPPLIER_CONTACTS_TBL;
select * from XXBCM_ORDER_HEADERS_TBL;
select * from XXBCM_ORDER_LINES_TBL;
select * from XXBCM_INVOICE_HOLDS_TBL;
select * from XXBCM_INVOICE_HEADERS_TBL;
select * from XXBCM_INVOICE_LINES_TBL;
