create or replace PACKAGE XXBCM_DATA_MIGRATION_PKG AUTHID CURRENT_USER
IS

PROCEDURE XXBCM_ADD_SUPPLIER_ADDRESS;
PROCEDURE XXBCM_ADD_SUPPLIER;
PROCEDURE XXBCM_ADD_SUPPLIER_CONTACT;
PROCEDURE XXBCM_ADD_ORDER_HEADERS;
PROCEDURE XXBCM_ADD_ORDER_LINES;
PROCEDURE XXBCM_ADD_INVOICE_HOLDS;
PROCEDURE XXBCM_ADD_INVOICE_HEADERS;
PROCEDURE XXBCM_ADD_INVOICE_LINES;

END XXBCM_DATA_MIGRATION_PKG;